# Defining the compose version
version: '3.9'

# Defining the services to be run
services:
  # Django application service
  app:
    # Using the current directory
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    # Updates to local code will be reflected to the running Docker container
    volumes:
      - ./app:/app
    # Command used to run the service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
