# Defining the compose version
version: '3.9'

# Defining the services to be run
services:
  # Django application service
  app:
    # Using the current directory
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    # Updates to local code will be reflected to the running Docker container
    volumes:
      - ./app:/app
    # Command used to run the service
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  # This wil be the hostname for the database on the network
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
